AWSTemplateFormatVersion: 2010-09-09
Description: AWs CloudFormation template yml

Resources:
  EffulgencetechVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: production
 
  EffulgencetechVPCigw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: stack
        Value: production
        
EffulgencetechVPCigw-attachment:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
    VpcId:
       Ref: EffulgencetechVPC
    InternetGatewayId:
       Ref: EffulgencetechVPCigw

  EffulgencetechVPCprivSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: EffulgencetechVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: stack
        Value: production  

EffulgencetechVPCpubSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: EffulgencetechVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: stack
        Value: production 

EffulgencetechVPCpubSNRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: EffulgencetechVPC
      Tags:
      - Key: stack
        Value: production

EffulgencetechVPCpubSNRTassocia:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: EffulgencetechVPCpubSN
      RouteTableId:
        Ref: EffulgencetechVPCpubSNRT

EffulgencetechVPCpubR:
    Type: AWS::EC2::Route
    DependsOn: GatewayToInternet
    Properties:
       RouteTableId:
         Ref: EffulgencetechVPCpubSNRT
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: EffulgencetechVPCigw

EffulgencetechVPCprivSNRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: EffulgencetechVPC
      Tags:
      - Key: stack
        Value: production


EffulgencetechVPCprivSNRTassocia:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: EffulgencetechVPCprivSN
      RouteTableId:
        Ref: EffulgencetechVPCprivSNRT